using E_commerce.Models;

namespace E_commerce.Abstractions
{
    public class AppliancesAbstractions
    {
        public static List<Product> GetProducts()
        {
            return new List<Product>
            {
             
                new Product { Id = 91,CreatedAt = DateTime.UtcNow, Name = "LG French Door Refrigerator", Brand = "LG", Price = 2199.99m, Category = "Appliances", SubCategory = "Refrigerators", Quantity = 15, Warranty = 24, Images = new string[] { "https://www.lg.com/content/dam/channel/wcms/ca_en/images/refrigerators/lrfxs3106s/gallery/450.jpg/jcr:content/renditions/thum-350x350.jpeg" } },
                new Product { Id = 92,CreatedAt = DateTime.UtcNow, Name = "Samsung Smart Refrigerator", Brand = "Samsung", Price = 2499.99m, Category = "Appliances", SubCategory = "Refrigerators", Quantity = 12, Warranty = 24, Images = new string[] { "https://assets.newatlas.com/dims4/default/1f9fd1d/2147483647/strip/true/crop/1080x720+0+0/resize/1080x720!/format/webp/quality/90/?url=https%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2Farchive%2Fsamsung-family-hub-2-fridge-6.jpg" } },
                new Product { Id = 93,CreatedAt = DateTime.UtcNow, Name = "Whirlpool Side-by-Side", Brand = "Whirlpool", Price = 1599.99m, Category = "Appliances", SubCategory = "Refrigerators", Quantity = 18, Warranty = 12, Images = new string[] { "https://images.webfronts.com/cache/meewbwwdimir.jpg?imgeng=/w_500/h_500/m_letterbox_ffffff_100" } },
                new Product { Id = 94,CreatedAt = DateTime.UtcNow, Name = "GE Profile Counter-Depth", Brand = "GE", Price = 2899.99m, Category = "Appliances", SubCategory = "Refrigerators", Quantity = 10, Warranty = 24, Images = new string[] { "https://aaappliancecenter.com/cdn/shop/files/604994_1.jpg?v=1692727708" } },
                new Product { Id = 95,CreatedAt = DateTime.UtcNow, Name = "Frigidaire Gallery", Brand = "Frigidaire", Price = 1399.99m, Category = "Appliances", SubCategory = "Refrigerators", Quantity = 20, Warranty = 12, Images = new string[] { "https://c.shld.net/rpx/i/s/i/spin/10038420/prod_26705292212?hei=450&wid=450" } },
                new Product { Id = 96,CreatedAt = DateTime.UtcNow, Name = "Bosch 800 Series", Brand = "Bosch", Price = 2699.99m, Category = "Appliances", SubCategory = "Refrigerators", Quantity = 8, Warranty = 24, Images = new string[] { "https://cdn.rona.ca/images/30855291_L.jpg" } },
                new Product { Id = 97,CreatedAt = DateTime.UtcNow, Name = "Haier Bottom Freezer", Brand = "Haier", Price = 1199.99m, Category = "Appliances", SubCategory = "Refrigerators", Quantity = 15, Warranty = 12, Images = new string[] { "https://bigdeals.lk/uploads/product/normal/hrrfdd4053pkglar.png" } },
                new Product { Id = 98,CreatedAt = DateTime.UtcNow, Name = "Maytag Wide French Door", Brand = "Maytag", Price = 1899.99m, Category = "Appliances", SubCategory = "Refrigerators", Quantity = 12, Warranty = 12, Images = new string[] { "https://images.webfronts.com/cache/meurghgqruxn.jpg?imgeng=/w_500/h_500/m_letterbox_ffffff_100" } },
                new Product { Id = 99,CreatedAt = DateTime.UtcNow, Name = "KitchenAid Counter Depth", Brand = "KitchenAid", Price = 2999.99m, Category = "Appliances", SubCategory = "Refrigerators", Quantity = 7, Warranty = 24, Images = new string[] { "https://www.kitchenaid.com/is/image/content/dam/global/kitchenaid/refrigeration/freestanding-refrigerator/images/hero-KRSC700HBS.tif?hei=600" } },
                new Product { Id = 100, CreatedAt = DateTime.UtcNow,Name = "Hisense Bottom Freezer", Brand = "Hisense", Price = 999.99m, Category = "Appliances", SubCategory = "Refrigerators", Quantity = 25, Warranty = 12, Images = new string[] { "https://www.liquidationelectromenagers.com/cdn/shop/products/532078_2_800x.jpg?v=1658424784" } },

                
                new Product { Id = 101,CreatedAt = DateTime.UtcNow, Name = "LG Front Load Washer", Brand = "LG", Price = 899.99m, Category = "Appliances", SubCategory = "Washing Machines", Quantity = 15, Warranty = 12, Images = new string[] { "https://www.lg.com/levant_en/images/washing-machines/md06011796/gallery/N02_dm-02.jpg" } },
                new Product { Id = 102,CreatedAt = DateTime.UtcNow, Name = "Samsung Smart Washer", Brand = "Samsung", Price = 799.99m, Category = "Appliances", SubCategory = "Washing Machines", Quantity = 18, Warranty = 12, Images = new string[] { "https://image-us.samsung.com/SamsungUS/home/home-appliances/washers/flex-washers/wv60m9900av/FlexWasher_Gallery1.jpg?$product-details-jpg$" } },
                new Product { Id = 103,CreatedAt = DateTime.UtcNow, Name = "Whirlpool Top Load", Brand = "Whirlpool", Price = 699.99m, Category = "Appliances", SubCategory = "Washing Machines", Quantity = 20, Warranty = 12, Images = new string[] { "https://www.thebrick.com/cdn/shop/products/shopify-image_b01333e7-5062-4132-9b34-04e3b167dda7_1500x.jpg?v=1701112307" } },
                new Product { Id = 104,CreatedAt = DateTime.UtcNow, Name = "GE UltraFresh Front Load", Brand = "GE", Price = 999.99m, Category = "Appliances", SubCategory = "Washing Machines", Quantity = 12, Warranty = 12, Images = new string[] { "https://geappliances.ca/medias/1200Wx1200H-A-PROFILE-LAUNDRY-PFW870SPVRS-FRONT.jpg?context=bWFzdGVyfGltYWdlc3wyMDc3ODZ8aW1hZ2UvanBlZ3xhR1l6TDJoa09TOHhNVEkzTmpVME56UTFOekExTkM4eE1qQXdWM2d4TWpBd1NGOUJMVkJTVDBaSlRFVXRURUZWVGtSU1dTMVFSbGM0TnpCVFVGWlNVeTFHVWs5T1ZDNXFjR2N8N2FjMGY0YjhiOGZhOTdmMTJmMTk1NDNkOWQxMTZiYWEyOTliMTJjZGEzOWRiMDM2OTVhYzZmY2I5NzY0ZmYwNw" } },
                new Product { Id = 105,CreatedAt = DateTime.UtcNow, Name = "Maytag Commercial Washer", Brand = "Maytag", Price = 1099.99m, Category = "Appliances", SubCategory = "Washing Machines", Quantity = 10, Warranty = 12, Images = new string[] { "https://www.trailappliances.com/media/catalog/product/M/H/MHN33PRCWW_1_35d6.jpg?auto=webp&format=pjpg&width=440&height=440&fit=cover" } },
                new Product { Id = 106,CreatedAt = DateTime.UtcNow, Name = "Bosch 500 Series", Brand = "Bosch", Price = 899.99m, Category = "Appliances", SubCategory = "Washing Machines", Quantity = 15, Warranty = 12, Images = new string[] { "https://5.imimg.com/data5/SELLER/Default/2020/9/SW/FG/BU/5593817/bosch-front-loading-8kg-wat2846win-white--500x500.jpg" } },
                new Product { Id = 107,CreatedAt = DateTime.UtcNow, Name = "Electrolux Front Load", Brand = "Electrolux", Price = 1099.99m, Category = "Appliances", SubCategory = "Washing Machines", Quantity = 12, Warranty = 12, Images = new string[] { "https://www.noelleeming.co.nz/dw/image/v2/BDMG_PRD/on/demandware.static/-/Sites-nlg-master-catalog/default/dw08e843f8/images/hi-res/22/D3/N224219_0.jpg?sw=765&sh=765" } },
                new Product { Id = 108,CreatedAt = DateTime.UtcNow, Name = "Amana Top Load", Brand = "Amana", Price = 499.99m, Category = "Appliances", SubCategory = "Washing Machines", Quantity = 25, Warranty = 12, Images = new string[] { "https://www.maysfieldappliance.ca/cdn/shop/files/20250507_164717_800x.jpg?v=1746973753" } },
                new Product { Id = 109,CreatedAt = DateTime.UtcNow, Name = "Speed Queen Top Load", Brand = "Speed Queen", Price = 1199.99m, Category = "Appliances", SubCategory = "Washing Machines", Quantity = 8, Warranty = 24, Images = new string[] { "https://www.pcrichard.com/dw/image/v2/BFXM_PRD/on/demandware.static/-/Sites-pcrichard-master-product-catalog/default/dw5ea6dacd/images/hires/Z_TC5003BN.jpg?sw=800&sh=800&sm=fit" } },
                new Product { Id = 110, CreatedAt = DateTime.UtcNow,Name = "Kenmore Elite Front Load", Brand = "Kenmore", Price = 899.99m, Category = "Appliances", SubCategory = "Washing Machines", Quantity = 15, Warranty = 12, Images = new string[] { "https://images-cdn.ubuy.co.in/636e7a137aa066371a5a08e8-kenmore-elite-41983-5-2-cu-ft-smart.jpg" } },

               
                new Product { Id = 111,CreatedAt = DateTime.UtcNow, Name = "LG Dual Inverter AC", Brand = "LG", Price = 599.99m, Category = "Appliances", SubCategory = "Air Conditioners", Quantity = 20, Warranty = 12, Images = new string[] { "https://www.lg.com/africa/images/split-air-conditioners/md06099357/gallery/medium02.jpg" } },
                new Product { Id = 112,CreatedAt = DateTime.UtcNow, Name = "Frigidaire Window AC", Brand = "Frigidaire", Price = 349.99m, Category = "Appliances", SubCategory = "Air Conditioners", Quantity = 25, Warranty = 12, Images = new string[] { "https://i.pcmag.com/imagery/reviews/01PbgmjnRkwagOqqYVtZs5H-4..v1569473522.jpg" } },
                new Product { Id = 113,CreatedAt = DateTime.UtcNow, Name = "GE Portable AC", Brand = "GE", Price = 499.99m, Category = "Appliances", SubCategory = "Air Conditioners", Quantity = 15, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/51Ai334cwbL.jpg" } },
                new Product { Id = 114,CreatedAt = DateTime.UtcNow, Name = "Midea U-Shaped AC", Brand = "Midea", Price = 399.99m, Category = "Appliances", SubCategory = "Air Conditioners", Quantity = 18, Warranty = 12, Images = new string[] { "https://bfasset.costco-static.com/U447IH35/as/xr886mm7s7n7789gt78gkrq6/1677429-847__1?auto=webp&amp;format=jpg&width=1200&height=1200&fit=bounds&canvas=1200,1200" } },
                new Product { Id = 115,CreatedAt = DateTime.UtcNow, Name = "Honeywell Portable AC", Brand = "Honeywell", Price = 449.99m, Category = "Appliances", SubCategory = "Air Conditioners", Quantity = 20, Warranty = 12, Images = new string[] { "https://i.ebayimg.com/images/g/3FAAAOSwUl9mqC3R/s-l1200.png" } },
                new Product { Id = 116, CreatedAt = DateTime.UtcNow,Name = "Toshiba Inverter AC", Brand = "Toshiba", Price = 549.99m, Category = "Appliances", SubCategory = "Air Conditioners", Quantity = 15, Warranty = 12, Images = new string[] { "https://4.imimg.com/data4/UD/TE/MY-6112547/toshiba-split-ac-500x500.jpg" } },
                new Product { Id = 117,CreatedAt = DateTime.UtcNow, Name = "Black+Decker Portable AC", Brand = "Black+Decker", Price = 399.99m, Category = "Appliances", SubCategory = "Air Conditioners", Quantity = 20, Warranty = 12, Images = new string[] { "https://mobileimages.lowes.com/productimages/1f159bbf-70ce-4477-b1d9-53a7cecf7728/67146016.jpeg" } },
                new Product { Id = 118,CreatedAt = DateTime.UtcNow, Name = "Danby Portable AC", Brand = "Danby", Price = 499.99m, Category = "Appliances", SubCategory = "Air Conditioners", Quantity = 15, Warranty = 12, Images = new string[] { "https://cdnweb.danby.com/wp-content/uploads/sites/3/2022/02/10141429/DPA120B9IBDB-6-Featured.jpg" } },
                new Product { Id = 119,CreatedAt = DateTime.UtcNow, Name = "Sharp Inverter AC", Brand = "Sharp", Price = 599.99m, Category = "Appliances", SubCategory = "Air Conditioners", Quantity = 12, Warranty = 12, Images = new string[] { "https://sieuthimaylanh.com/uploads/product/02_2023/may-lanh-sharp-inverter-2-0hp-ah-x18zew-model-2023-hp1.webp" } },
                new Product { Id = 120, CreatedAt = DateTime.UtcNow,Name = "Haier Window AC", Brand = "Haier", Price = 299.99m, Category = "Appliances", SubCategory = "Air Conditioners", Quantity = 25, Warranty = 12, Images = new string[] { "https://5.imimg.com/data5/TH/VX/MY-17549931/haier-window-ac-500x500.jpg" } },

               
                new Product { Id = 121,CreatedAt = DateTime.UtcNow, Name = "Bosch 800 Series", Brand = "Bosch", Price = 999.99m, Category = "Appliances", SubCategory = "Dishwashers", Quantity = 12, Warranty = 12, Images = new string[] { "https://www.westcoastappliance.ca/files/image/attachment/72087/preview_SHE78CM5N-2.jpg" } },
                new Product { Id = 122,CreatedAt = DateTime.UtcNow, Name = "KitchenAid Built-In", Brand = "KitchenAid", Price = 1099.99m, Category = "Appliances", SubCategory = "Dishwashers", Quantity = 10, Warranty = 12, Images = new string[] { "https://mobileimages.lowes.com/productimages/d094c2a9-1140-4616-a8d8-ccb888b3dd7a/00616736.jpg?size=pdhism" } },
                new Product { Id = 123,CreatedAt = DateTime.UtcNow, Name = "GE Profile Top Control", Brand = "GE", Price = 899.99m, Category = "Appliances", SubCategory = "Dishwashers", Quantity = 15, Warranty = 12, Images = new string[] { "https://geappliances.ca/medias/1200Wx1200H-A-24-INCH-DISHWASHER-FINGERPRINT-RESISTANT-STAINLESS-STEEL-PBT700SSVFS-GE-PROFILE-FRONT.jpg?context=bWFzdGVyfGltYWdlc3wxMDYxMDl8aW1hZ2UvanBlZ3xhR00zTDJnME15OHhNVGMyTlRreU5UUTNPRFF6TUM4eE1qQXdWM2d4TWpBd1NGOUJMVEkwTFVsT1EwZ3RSRWxUU0ZkQlUwaEZVaTFHU1U1SFJWSlFVa2xPVkMxU1JWTkpVMVJCVGxRdFUxUkJTVTVNUlZOVExWTlVSVVZNTFZCQ1ZEY3dNRk5UVmtaVExVZEZMVkJTVDBaSlRFVXRSbEpQVGxRdWFuQm58MWM2YjVmNWViMzVkNTNkOGMxMjBhODcyMzk0MDEyODkwZGMyNjFkMDU0MmRmNjc2NGFlNWJkZWE0MGIzYmU5ZA" } },
                new Product { Id = 124,CreatedAt = DateTime.UtcNow, Name = "Maytag Front Control", Brand = "Maytag", Price = 799.99m, Category = "Appliances", SubCategory = "Dishwashers", Quantity = 18, Warranty = 12, Images = new string[] { "https://www.westcoastappliance.ca/files/image/attachment/17537/preview_MDB4949SKW_4.jpg" } },
                new Product { Id = 125, CreatedAt = DateTime.UtcNow,Name = "Samsung StormWash", Brand = "Samsung", Price = 849.99m, Category = "Appliances", SubCategory = "Dishwashers", Quantity = 12, Warranty = 12, Images = new string[] { "https://images.thdstatic.com/productImages/8d94748a-f85d-4e66-bc4c-3fcc298e840c/svn/fingerprint-resistant-matte-black-steel-samsung-built-in-dishwashers-dw90f89t0umt-64_600.jpg" } },

             
                new Product { Id = 126,CreatedAt = DateTime.UtcNow, Name = "Samsung QLED 4K TV", Brand = "Samsung", Price = 1299.99m, Category = "Appliances", SubCategory = "Televisions", Quantity = 15, Warranty = 12, Images = new string[] { "https://megasmart.ge/wp-content/uploads/2025/01/QE55Q70DAUXRU-2.png" } },
                new Product { Id = 127,CreatedAt = DateTime.UtcNow, Name = "LG OLED C1 Series", Brand = "LG", Price = 1799.99m, Category = "Appliances", SubCategory = "Televisions", Quantity = 10, Warranty = 12, Images = new string[] { "https://www.lg.com/ae/images/tvs/md07523258/D-05.jpg" } },
                new Product { Id = 128,CreatedAt = DateTime.UtcNow, Name = "Sony Bravia XR OLED", Brand = "Sony", Price = 1999.99m, Category = "Appliances", SubCategory = "Televisions", Quantity = 8, Warranty = 12, Images = new string[] { "https://klg.ge/wp-content/uploads/2024/02/XR-77A80L.jpg" } },
                new Product { Id = 129,CreatedAt = DateTime.UtcNow, Name = "TCL 6-Series Roku TV", Brand = "TCL", Price = 899.99m, Category = "Appliances", SubCategory = "Televisions", Quantity = 20, Warranty = 12, Images = new string[] { "https://www.tcl.com/usca/content/dam/tcl/product/home-theater/6-series/super-bowl-screen-fill/R635-NFL-Front.png" } },
                new Product { Id = 130,CreatedAt = DateTime.UtcNow, Name = "Vizio M-Series Quantum", Brand = "Vizio", Price = 799.99m, Category = "Appliances", SubCategory = "Televisions", Quantity = 18, Warranty = 12, Images = new string[] { "https://i5.walmartimages.com/asr/3538d30f-7b0c-4b24-bec6-635e9c848a18.b4a8ad477544ed2bfe51c781f63eeddc.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF" } },
                new Product { Id = 131,CreatedAt = DateTime.UtcNow, Name = "Hisense ULED U7G", Brand = "Hisense", Price = 999.99m, Category = "Appliances", SubCategory = "Televisions", Quantity = 15, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/81ZiU79k8bL._AC_SL1500_.jpg" } },
                new Product { Id = 132,CreatedAt = DateTime.UtcNow, Name = "Insignia Fire TV", Brand = "Insignia", Price = 499.99m, Category = "Appliances", SubCategory = "Televisions", Quantity = 25, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/81Q0HLbeLbL._UF1000,1000_QL80_.jpg" } },
                new Product { Id = 133,CreatedAt = DateTime.UtcNow, Name = "Sharp Aquos 4K", Brand = "Sharp", Price = 699.99m, Category = "Appliances", SubCategory = "Televisions", Quantity = 15, Warranty = 12, Images = new string[] { "https://res.cloudinary.com/sharp-consumer-eu/image/fetch/w_3000,f_auto/https://s3.infra.brandquad.io/accounts-media/SHRP/DAM/origin/ebd97d00-8f26-11ea-8423-a2a23790eccc.jpg" } },
                new Product { Id = 134,CreatedAt = DateTime.UtcNow, Name = "Philips Ambilight TV", Brand = "Philips", Price = 1199.99m, Category = "Appliances", SubCategory = "Televisions", Quantity = 12, Warranty = 12, Images = new string[] { "https://cdn.cdon.com/media-dynamic/images/product/cloud/store/TV/000/149/995/802/149995802-287575223-11453-org.jpg?cache=133905426376603729&imWidth=600" } },
                new Product { Id = 135,CreatedAt = DateTime.UtcNow, Name = "Panasonic HDR 4K", Brand = "Panasonic", Price = 1099.99m, Category = "Appliances", SubCategory = "Televisions", Quantity = 10, Warranty = 12, Images = new string[] { "https://store.in.panasonic.com/media/catalog/product/cache/40b589206cef99ab7dca1586fe425968/t/h/th-43mx660dx_info_1_new.webp" } },

               
                new Product { Id = 136,CreatedAt = DateTime.UtcNow, Name = "Panasonic Microwave", Brand = "Panasonic", Price = 149.99m, Category = "Appliances", SubCategory = "Microwaves", Quantity = 20, Warranty = 12, Images = new string[] { "https://static.my.ge/mymarket/photos/large/0616/30983279_1.jpg?v=0" } },
                new Product { Id = 137,CreatedAt = DateTime.UtcNow, Name = "Toshiba Countertop", Brand = "Toshiba", Price = 129.99m, Category = "Appliances", SubCategory = "Microwaves", Quantity = 25, Warranty = 12, Images = new string[] { "https://d1pjg4o0tbonat.cloudfront.net/content/dam/toshiba-aem/ca/cooking-appliances/microwave-ovens/ml3-em13pa(ss)ca/left.png/jcr:content/renditions/left.webp" } },
                new Product { Id = 138,CreatedAt = DateTime.UtcNow, Name = "GE Over-the-Range", Brand = "GE", Price = 199.99m, Category = "Appliances", SubCategory = "Microwaves", Quantity = 15, Warranty = 12, Images = new string[] { "https://assets.skulytics.io/assets/images/PEB7226DFWW-63387871.webp" } },
                new Product { Id = 139, Name = "Samsung Smart Microwave", Brand = "Samsung", Price = 179.99m, Category = "Appliances", SubCategory = "Microwaves", Quantity = 18, Warranty = 12, Images = new string[] { "https://metromart.ge/website/image/product.image/29515/image/400x400" } },
                new Product { Id = 140, Name = "Whirlpool Built-In", Brand = "Whirlpool", Price = 249.99m, Category = "Appliances", SubCategory = "Microwaves", Quantity = 12, Warranty = 12, Images = new string[] { "https://cdn.allmarket.ge/2405/47/17/82/186081f190a840008b0ee89821450d0c/69726-573804.jpg" } },

                new Product { Id = 141, Name = "Cuisinart Electric Kettle", Brand = "Cuisinart", Price = 79.99m, Category = "Appliances", SubCategory = "Kitchen Accessories", Quantity = 15, Warranty = 12, Images = new string[] { "https://www.cuisinart.com/dw/image/v2/ABAF_PRD/on/demandware.static/-/Sites-master-us/default/dw1c575523/images/large/CPK-17P1_A.jpg?sw=1200&sh=1200&sm=fit" } },
                new Product { Id = 142, Name = "Hamilton Beach Kettle", Brand = "Hamilton Beach", Price = 39.99m, Category = "Appliances", SubCategory = "Kitchen Accessories", Quantity = 20, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/71zJShDoPsL.jpg" } },
                
             
                new Product { Id = 143, Name = "Ninja Professional Blender", Brand = "Ninja", Price = 89.99m, Category = "Appliances", SubCategory = "Kitchen Accessories", Quantity = 18, Warranty = 12, Images = new string[] { "https://res.cloudinary.com/sharkninja-na/image/upload/c_fit,h_600,w_600/v1/SharkNinja-NA/BN751_01?_a=BAKAACDX0" } },
                new Product { Id = 144, Name = "Vitamix Explorian", Brand = "Vitamix", Price = 349.99m, Category = "Appliances", SubCategory = "Kitchen Accessories", Quantity = 10, Warranty = 12, Images = new string[] { "https://www.biopapa.lv/wp-content/uploads/2023/11/Blenderis-Vitamix-Explorian-E310-melns.png" } },
                new Product { Id = 145, Name = "Oster Reverse Crush", Brand = "Oster", Price = 59.99m, Category = "Appliances", SubCategory = "Kitchen Accessories", Quantity = 20, Warranty = 12, Images = new string[] { "https://images.thdstatic.com/productImages/5528a46a-8b3f-423f-ba78-1eaaa7566bac/svn/brushed-nickel-oster-countertop-blenders-985118430m-64_600.jpg" } },
                new Product { Id = 146, Name = "KitchenAid K150", Brand = "KitchenAid", Price = 129.99m, Category = "Appliances", SubCategory = "Kitchen Accessories", Quantity = 15, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/71lPqNOfkHL.jpg" } },
                
                
                new Product { Id = 147, Name = "Keurig K-Elite", Brand = "Keurig", Price = 179.99m, Category = "Appliances", SubCategory = "Kitchen Accessories", Quantity = 15, Warranty = 12, Images = new string[] { "https://djd1xqjx2kdnv.cloudfront.net/photos/32/34/444948_16366_XXL.jpg" } },
                new Product { Id = 148, Name = "Ninja Hot & Cold Brew", Brand = "Ninja", Price = 199.99m, Category = "Appliances", SubCategory = "Kitchen Accessories", Quantity = 12, Warranty = 12, Images = new string[] { "https://media.kohlsimg.com/is/image/kohls/3397064?wid=620&hei=620&op_sharpen=1" } },
                
               
                new Product { Id = 149, Name = "Breville Smart Oven", Brand = "Breville", Price = 249.99m, Category = "Appliances", SubCategory = "Kitchen Accessories", Quantity = 10, Warranty = 12, Images = new string[] { "https://assets.surlatable.com/m/48909279177e4c72/72_dpi_webp-3179272_1022_vs" } },
                new Product { Id = 150, Name = "Black+Decker Toaster Oven", Brand = "Black+Decker", Price = 89.99m, Category = "Appliances", SubCategory = "Kitchen Accessories", Quantity = 20, Warranty = 12, Images = new string[] { "https://media.hearstapps.com/vader-prod.s3.amazonaws.com/1622819785-41ln8QwMwqL._SL500_.jpg?width=600" } },

               
                new Product { Id = 151, Name = "Dyson V11 Absolute", Brand = "Dyson", Price = 599.99m, Category = "Appliances", SubCategory = "Vacuum Cleaners", Quantity = 10, Warranty = 12, Images = new string[] { "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/primary/419648-01.png?$responsive$&cropPathE=mobile&fit=stretch,1&wid=440" } },
                new Product { Id = 152, Name = "Shark Navigator Lift-Away", Brand = "Shark", Price = 199.99m, Category = "Appliances", SubCategory = "Vacuum Cleaners", Quantity = 15, Warranty = 12, Images = new string[] { "https://freemans.scene7.com/is/image/OttoUK/466w/shark-lift-away-upright-vacuum-cleaner-nv602uk~49B720FRSP.jpg" } },
                new Product { Id = 153, Name = "iRobot Roomba i7+", Brand = "iRobot", Price = 799.99m, Category = "Appliances", SubCategory = "Vacuum Cleaners", Quantity = 8, Warranty = 12, Images = new string[] { "https://www.irobot.co.uk/on/demandware.static/-/Sites-master-catalog-irobot/default/dwe56070cb/images/large/bundles/EMEA_i7plus_m6g_1.jpg" } },
                new Product { Id = 154, Name = "Bissell CleanView", Brand = "Bissell", Price = 129.99m, Category = "Appliances", SubCategory = "Vacuum Cleaners", Quantity = 20, Warranty = 12, Images = new string[] { "https://www.smithscity.co.nz/content/productimages/bissell-cleanview-vacuum-9064885-1.jpg?width=1320&height=860&fit=bounds&bg-color=fff&canvas=1320%2C860" } },
                new Product { Id = 155, Name = "Hoover WindTunnel", Brand = "Hoover", Price = 149.99m, Category = "Appliances", SubCategory = "Vacuum Cleaners", Quantity = 18, Warranty = 12, Images = new string[] { "https://kaleidoscope.scene7.com/is/image/OttoUK/600w/Hoover-HP1-Corded-Bagless-Cylinder-Vacuum-Cleaner---HP105HM~97W594FRSP.jpg" } },
                new Product { Id = 156, Name = "Eureka PowerSpeed", Brand = "Eureka", Price = 99.99m, Category = "Appliances", SubCategory = "Vacuum Cleaners", Quantity = 25, Warranty = 12, Images = new string[] { "https://www.staples-3p.com/s7/is/image/Staples/68A962EA-4056-4134-88E76F64326D8279_sc7?wid=700&hei=700" } },
                new Product { Id = 157, Name = "Miele Complete C3", Brand = "Miele", Price = 699.99m, Category = "Appliances", SubCategory = "Vacuum Cleaners", Quantity = 8, Warranty = 12, Images = new string[] { "https://cdn11.bigcommerce.com/s-eont72k65g/images/stencil/1280x1280/products/518/1678/2801__60951.1581088696.jpg?c=2" } },
                new Product { Id = 158, Name = "LG CordZero A9", Brand = "LG", Price = 499.99m, Category = "Appliances", SubCategory = "Vacuum Cleaners", Quantity = 12, Warranty = 12, Images = new string[] { "https://www.nfm.com/dw/image/v2/BDFM_PRD/on/demandware.static/-/Sites-nfm-master-catalog/default/dw384db07f/images/061/02/61027181-8.jpg?sw=1000&sh=1000&sm=fit" } },
                new Product { Id = 159, Name = "Samsung Jet 90", Brand = "Samsung", Price = 449.99m, Category = "Appliances", SubCategory = "Vacuum Cleaners", Quantity = 10, Warranty = 12, Images = new string[] { "https://vacuumwars.com/wp-content/uploads/2023/05/Samsung-Jet-90-Review-1024x538.jpg" } },
                new Product { Id = 160, Name = "Tineco Pure One S12", Brand = "Tineco", Price = 399.99m, Category = "Appliances", SubCategory = "Vacuum Cleaners", Quantity = 12, Warranty = 12, Images = new string[] { "https://cdn.mydeal.com.au/44283/tineco-pure-one-s12-platinum-cordless-stick-vacuum-with-led-brush-1567376_06.jpg?v=637175379459476955" } },

               
                new Product { Id = 161, Name = "LG Electric Dryer", Brand = "LG", Price = 799.99m, Category = "Appliances", SubCategory = "Drying Machines", Quantity = 12, Warranty = 12, Images = new string[] { "https://www.pcrichard.com/dw/image/v2/BFXM_PRD/on/demandware.static/-/Sites-pcrichard-master-product-catalog/default/dw5a63ae97/images/hires/AZ5_DLE6100M.jpg?sw=800&sh=800&sm=fit" } },
                new Product { Id = 162, Name = "Samsung Ventless Dryer", Brand = "Samsung", Price = 899.99m, Category = "Appliances", SubCategory = "Drying Machines", Quantity = 10, Warranty = 12, Images = new string[] { "https://assets.wfcdn.com/im/90973261/resize-h755-w755%5Ecompr-r85/2610/261075605/Bespoke+7.8+cu.+ft.+Ultra+Capacity+Ventless+Hybrid+Heat+Pump+Dryer+with+AI+Optimal+Dry.jpg" } },
                new Product { Id = 163, Name = "Whirlpool Gas Dryer", Brand = "Whirlpool", Price = 699.99m, Category = "Appliances", SubCategory = "Drying Machines", Quantity = 15, Warranty = 12, Images = new string[] { "https://mobileimages.lowes.com/productimages/72cee256-4e5f-4ceb-96c5-1b0c989aa531/67348994.png?size=pdhism" } },
                new Product { Id = 164, Name = "GE Smart Dryer", Brand = "GE", Price = 749.99m, Category = "Appliances", SubCategory = "Drying Machines", Quantity = 12, Warranty = 12, Images = new string[] { "https://images.thdstatic.com/productImages/7ad89a8c-29b5-412b-b92b-31893ab98e54/svn/black-samsung-electric-dryers-dve55cg7100v-64_600.jpg" } },
                new Product { Id = 165, Name = "Maytag Commercial Dryer", Brand = "Maytag", Price = 999.99m, Category = "Appliances", SubCategory = "Drying Machines", Quantity = 8, Warranty = 12, Images = new string[] { "https://cdn11.bigcommerce.com/s-6ffbwvze5a/images/stencil/1280x1280/products/157/428/MDEMDG20PD__29900.1548113112.jpg?c=2" } },
                new Product { Id = 166, Name = "Electrolux Front Load", Brand = "Electrolux", Price = 1099.99m, Category = "Appliances", SubCategory = "Drying Machines", Quantity = 10, Warranty = 12, Images = new string[] { "https://www.nfm.com/dw/image/v2/BDFM_PRD/on/demandware.static/-/Sites-nfm-master-catalog/default/dw5c636e35/images/064/94/64941933-4.jpg?sw=1000&sh=1000&sm=fit" } },
                new Product { Id = 167, Name = "Amana Electric Dryer", Brand = "Amana", Price = 499.99m, Category = "Appliances", SubCategory = "Drying Machines", Quantity = 20, Warranty = 12, Images = new string[] { "https://cdn.salla.sa/lrnmB/39867e95-5391-4b0a-ae6c-a1a9dfe46737-748.77650897227x1000-pUDjgBeNysUIe802dEWTNyuW6Zg72ajcMtPQkEFf.png" } },
                new Product { Id = 168, Name = "Speed Queen Dryer", Brand = "Speed Queen", Price = 1199.99m, Category = "Appliances", SubCategory = "Drying Machines", Quantity = 8, Warranty = 24, Images = new string[] { "https://images.webfronts.com/cache/frqywbflkfqj.jpg" } },
                new Product { Id = 169, Name = "Bosch Ventless", Brand = "Bosch", Price = 1099.99m, Category = "Appliances", SubCategory = "Drying Machines", Quantity = 10, Warranty = 12, Images = new string[] { "https://linqcdn.avbportal.com/images/6f25bc9a-9f4d-4ed8-a3a4-49f10b289f9e.jpg?w=640" } },
                new Product { Id = 170, Name = "Kenmore Elite Dryer", Brand = "Kenmore", Price = 899.99m, Category = "Appliances",SubCategory = "Drying Machines", Quantity = 10, Warranty = 12, Images = new string[] { "https://crdms.images.consumerreports.org/f_auto,w_1200/prod/products/cr/models/387747-electricdryers-kenmore-elite61632.jpg" } },
                new Product { Id = 171, Name = "GE Profile Smart Slide-In Gas Range", Brand = "GE", Price = 2299.00m, Category = "Appliances", SubCategory = "Stoves", Quantity = 12, Warranty = 24, Images = new string[] { "https://images.webfronts.com/cache/frsskaamgbji.jpg?imgeng=/w_1920/h_1920/m_letterbox_ffffff_100" } },

new Product { Id = 172, Name = "Samsung Smart Slide-In Electric Range", Brand = "Samsung", Price = 1499.00m, Category = "Appliances", SubCategory = "Stoves", Quantity = 15, Warranty = 24, Images = new string[] { "https://image-us.samsung.com/SamsungUS/home/home-appliances/ranges/electric/nse6dg8100mtaa/NSE6DG8100MT_SCOM_0003_NSE6DG8100MT_009_LPerspective_Matte_Black_STSS.jpg?$product-details-jpg$" } },
new Product { Id = 173, Name = "LG InstaView Electric Slide-In Range", Brand = "LG", Price = 1899.00m, Category = "Appliances", SubCategory = "Stoves", Quantity = 8, Warranty = 24, Images = new string[] { "https://www.lg.com/content/dam/channel/wcms/ca_en/images/ranges-ovens/lses6338f_arsllca_enci_ca_en_c/gallery/DZ-2.jpg" } },
new Product { Id = 174, Name = "Frigidaire Gallery Gas Range", Brand = "Frigidaire", Price = 1199.00m, Category = "Appliances", SubCategory = "Stoves", Quantity = 10, Warranty = 12, Images = new string[] { "https://mobileimages.lowes.com/productimages/1002e9a7-1dd8-432b-b241-249a877595d2/04432369.jpg" } },
new Product { Id = 175, Name = "Bosch 800 Series Induction Slide-In Range", Brand = "Bosch", Price = 3299.00m, Category = "Appliances", SubCategory = "Stoves", Quantity = 6, Warranty = 24, Images = new string[] { "https://images.webfronts.com/cache/frzpsyfnpsvk.webp?imgeng=/w_500/h_500/m_letterbox_ffffff_100" } },
new Product { Id = 176, Name = "Whirlpool Freestanding Electric Range", Brand = "Whirlpool", Price = 799.00m, Category = "Appliances", SubCategory = "Stoves", Quantity = 20, Warranty = 12, Images = new string[] { "https://aaappliancecenter.com/cdn/shop/files/611130_1.jpg?v=1692728622" } },
new Product { Id = 177, Name = "KitchenAid Dual Fuel Range", Brand = "KitchenAid", Price = 3199.00m, Category = "Appliances", SubCategory = "Stoves", Quantity = 7, Warranty = 24, Images = new string[] { "https://images.webfronts.com/cache/mefnateyetid.jpg?imgeng=/w_500/h_500/m_letterbox_ffffff_100" } },
new Product { Id = 178, Name = "Amana Electric Range", Brand = "Amana", Price = 649.00m, Category = "Appliances", SubCategory = "Stoves", Quantity = 18, Warranty = 12, Images = new string[] { "https://www.amana.com/is/image/content/dam/global/shot-lists/2022/p220500ac/additional-p220500ac-017z.tif?$PRODUCT-FEATURE$" } },
new Product { Id = 179, Name = "Maytag Freestanding Gas Range", Brand = "Maytag", Price = 1099.00m, Category = "Appliances", SubCategory = "Stoves", Quantity = 11, Warranty = 24, Images = new string[] { "https://assets.skulytics.io/assets/images/MGR6600PZ-75596356.webp" } },
new Product { Id = 180, Name = "ZLINE Dual Fuel Range 36-Inch", Brand = "ZLINE", Price = 2999.00m, Category = "Appliances", SubCategory = "Stoves", Quantity = 5, Warranty = 36, Images = new string[] { "https://thehomeselection.com/cdn/shop/products/zline--professional--black--stainless--steel--range--RABZ-36-G--hero.jpg?v=1643096671" } }
 };
        }
    }
}