using E_commerce.Models;
using static System.Net.WebRequestMethods;

namespace E_commerce.Abstractions
{
    public class It_EquipmentAbstractions
    {
        public static List<Product> GetProducts()
        {
            return new List<Product>
            {
                
                new Product { Id = 1,CreatedAt = DateTime.UtcNow, Name = "MacBook Pro 16-inch M1 Pro", Brand = "Apple", Price = 2399.00m, Category = "IT Equipment", SubCategory = "Laptops", Quantity = 50, Warranty = 12, Images = new string[] { "https://www.letemsvetemapplem.eu/wp-content/uploads/2023/11/MacBook-Pro-M3-Max-LsA-29.jpg", "https://i.ebayimg.com/images/g/AOYAAOSw2dxjxdjA/s-l1200.jpg","https://imageservice.asgoodasnew.com/540/17277/15/title-0000.jpg" } },
                new Product { Id = 2,CreatedAt = DateTime.UtcNow, Name = "Dell XPS 15 9520", Brand = "Dell", Price = 1899.99m, Category = "IT Equipment", SubCategory = "Laptops", Quantity = 45, Warranty = 12, Images = new string[] { "https://sm.pcmag.com/pcmag_au/review/d/dell-xps-1/dell-xps-15-oled-9520_g88x.jpg", "https://cdn.mos.cms.futurecdn.net/kjL8s668oDqPpnerRdZ8Re-1200-80.jpg", "https://www.mega.pk/items_images/Dell+XPS+15+9520+Core+i7+12th+Generation+16GB+RAM+1TB+SSD+4GB+RTX+3050Ti+Windows+11+Price+in+Pakistan%2C+Specifications%2C+Features_-_24435.webp" } },
                new Product { Id = 3,CreatedAt = DateTime.UtcNow, Name = "ThinkPad X1 Carbon Gen 9", Brand = "Lenovo", Price = 1699.00m, Category = "IT Equipment", SubCategory = "Laptops", Quantity = 60, Warranty = 24, Images = new string[] { "https://unicom.ge/files/products/SqJg5x7XLGe2nJfGzdTm37cXxWfUa7.jpg", "https://i.ebayimg.com/images/g/vNUAAOSwQi9j2ZCS/s-l400.jpg","https://isurve.ge/cdn/shop/files/1-min_ab643e6e-10c4-47b6-b5e2-d4729b50e379_x632.jpg?v=1733744479" } },
                new Product { Id = 4,CreatedAt = DateTime.UtcNow, Name = "ROG Zephyrus G14", Brand = "ASUS", Price = 1499.99m, Category = "IT Equipment", SubCategory = "Laptops", Quantity = 30, Warranty = 12, Images = new string[] { "https://i5.walmartimages.com/seo/ASUS-ROG-Zephyrus-G14-GA401QM-XS98Q-AMD-Ryzen-9-5900HS-4-6-GHz-Win-10-Pro-GF-RTX-3060-32-GB-RAM-1-TB-SSD-NVMe-14-2560-x-1440-WQHD-120-Hz-Wi-Fi-6-moon_a73a68d0-3e85-4a29-8391-ea0ba3cafab0.e7e8d9dfdfd3140a1d25bdfde7001b49.jpeg", "https://dlcdnwebimgs.asus.com/gain/7583764C-92E3-413D-A5AD-4CB7D9713802/w1000/h732", "https://dlcdnwebimgs.asus.com/gain/98AA0AFE-420A-4EE7-AAE2-6E813FA6A7CE/w1000/h732" } },
                new Product { Id = 5,CreatedAt = DateTime.UtcNow, Name = "HP Spectre x360 14", Brand = "HP", Price = 1399.99m, Category = "IT Equipment", SubCategory = "Laptops", Quantity = 40, Warranty = 12, Images = new string[] { "https://s3.zoommer.ge/site/3cc35c50-58ac-4fde-b99c-07a4ba084642_Thumb.jpeg", "https://www.hp.com/ca-en/shop/Html/Merch/Images/c08745208_1750x1285.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJsFo4sNurYpNvb2Xlkmm7E13Dc4GeHrHU3g&s" } },
                new Product { Id = 6,CreatedAt = DateTime.UtcNow, Name = "MSI GE76 Raider", Brand = "MSI", Price = 2199.99m, Category = "IT Equipment", SubCategory = "Laptops", Quantity = 25, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/617fteEclkL._AC_SL1200_.jpg", "https://m.media-amazon.com/images/I/51Q1cRNQ7JS.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi1t-tyHw5n2v2q3dPDGqkBohs00PK5Q5w2g&s" } },
                new Product { Id = 7,CreatedAt = DateTime.UtcNow, Name = "Acer Predator Helios 300", Brand = "Acer", Price = 1299.99m, Category = "IT Equipment", SubCategory = "Laptops", Quantity = 35, Warranty = 12, Images = new string[] { "https://assets.ee.ge/elit-product-mobile-images/IMG-000038642_79-1.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyyXr4KN8aMW_zOWRSNS2btVBaCg93rOq1_Q&s", "https://gigant.ge/images/detailed/16/acer-predator-helios-300-ph317-51-nh.q29er.007-gigant.ge-acer-predator-helios-300-ph317-51-nh.q29er.007.jpg" } },
                new Product { Id = 8,CreatedAt = DateTime.UtcNow, Name = "Razer Blade 15", Brand = "Razer", Price = 1999.99m, Category = "IT Equipment", SubCategory = "Laptops", Quantity = 20, Warranty = 12, Images = new string[] { "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz2i6vWYAJliRjyutx0aOLbPRPbr_biHsirA&s", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMU9YLbkPbU7JPw670eVsmgSpKc2yh9q0ZxQ&s", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9jPU8D2x7iP74x_JzNbjwBJmu9HHCDiO7hA&s" } },
                new Product { Id = 9,CreatedAt = DateTime.UtcNow, Name = "LG Gram 17", Brand = "LG", Price = 1699.99m, Category = "IT Equipment", SubCategory = "Laptops", Quantity = 30, Warranty = 12, Images = new string[] { "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxNvhGxTXqKVjnGXqaG3lHmKdU7TNVj6aQ1g&s", "https://www.lg.com/us/images/business/laptops/md07502492/feature/gram-17Z90N-DS-01-LG-gram-17-M.jpg", "https://i5.walmartimages.com/seo/Open-Box-LG-GRAM-17-2560X1600-I7-1260P-16GB-512GB-SSD-17Z90Q-K-AAC7U1-GRAY_e993f2c8-ed6b-48c6-aebb-5adba4fe994f.e332ab170a0d4920cb47fd9b95219071.jpeg" } },

                
                new Product { Id = 10,CreatedAt = DateTime.UtcNow, Name = "iMac 24-inch M1", Brand = "Apple", Price = 1299.00m, Category = "IT Equipment", SubCategory = "Desktop Computers", Quantity = 35, Warranty = 12, Images = new string[] { "https://assets.hardwarezone.com/img/2021/05/imac-intro.jpg", "https://images.openai.com/thumbnails/url/sixcolors.com...turn0image1","https://images.openai.com/thumbnails/url/amazon.com...turn0image2"} },
                new Product { Id = 11,CreatedAt = DateTime.UtcNow, Name = "Dell XPS 8940", Brand = "Dell", Price = 999.99m, Category = "IT Equipment", SubCategory = "Desktop Computers", Quantity = 40, Warranty = 12, Images = new string[] { "https://i.dell.com/is/image/DellContent//content/dam/images/products/desktops-and-all-in-ones/xps/8940-rkl/xs8940-csy-00015rf-bk-no-odd-rkl.psd?chrss=full&fmt=pjpg&hei=3329&imwidth=5000&pscan=auto&qlt=100%2C1&resMode=sharp2&scl=1&size=2297%2C3329&wid=2297", "https://i.dell.com/is/image/DellContent//content/dam/images/products/desktops-and-all-in-ones/xps/8940-rkl/xs8940-xsy-00010rf-bk-rkl.psd?chrss=full&fmt=png-alpha&hei=402&pscan=auto&qlt=100%2C1&resMode=sharp2&scl=1&size=660%2C402&wid=660", } },
                new Product { Id = 12,CreatedAt = DateTime.UtcNow, Name = "HP Pavilion Gaming Desktop", Brand = "HP", Price = 899.99m, Category = "IT Equipment", SubCategory = "Desktop Computers", Quantity = 50, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/71aceGtIm%2BL.jpg","https://store.hp.com/app/assets/images/uploads/prod/hp-pavilion-gaming-desktop-review-hero1589983682725190.jpg", "https://i5.walmartimages.com/seo/HP-Pavilion-Gaming-R5-1650-Super-8GB-256GB-Gaming-Desktop-Tower_086c5929-bcba-457a-ae8c-7cb41625245e.09b250d91deefc1940e7af15e8373c5a.jpeg" } },
                new Product { Id = 13,CreatedAt = DateTime.UtcNow, Name = "Lenovo ThinkCentre M90a", Brand = "Lenovo", Price = 1099.00m, Category = "IT Equipment", SubCategory = "Desktop Computers", Quantity = 30, Warranty = 12, Images = new string[] { "https://sm.pcmag.com/pcmag_au/review/l/lenovo-leg/lenovo-legion-tower-5i-gen-8-2024_qgfh.jpg","https://assets-prd.ignimgs.com/2024/10/28/legion-5-1730146293638.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSY78maOkcW1ITNnajfVCh79X2ZCbplG6kNez8kAOnoilWmHjoEheJwW_1flReI6tOGrA&usqp=CAU" } },
                new Product { Id = 14,CreatedAt = DateTime.UtcNow, Name = "ASUS ROG Strix G15", Brand = "ASUS", Price = 1499.99m, Category = "IT Equipment", SubCategory = "Desktop Computers", Quantity = 25, Warranty = 12, Images = new string[] { "https://bios.ge/images/detailed/23/%E1%83%9E%E1%83%94%E1%83%A0%E1%83%A1%E1%83%9D%E1%83%9C%E1%83%90%E1%83%9A%E1%83%A3%E1%83%A0%E1%83%98_%E1%83%99%E1%83%9D%E1%83%9B%E1%83%9E%E1%83%98%E1%83%A3%E1%83%A2%E1%83%94%E1%83%A0%E1%83%98_Asus_ROG_Strix_G15.png", "https://dlcdnwebimgs.asus.com/gain/F5A260D0-CB75-45E2-A632-521DDC5F28BE/w717/h525", "https://dlcdnwebimgs.asus.com/gain/6C7E48F7-F321-48A6-9B8D-C8470F9700DF/w717/h525" } },
                new Product { Id = 15,CreatedAt = DateTime.UtcNow, Name = "Acer Aspire TC-390", Brand = "Acer", Price = 599.99m, Category = "IT Equipment", SubCategory = "Desktop Computers", Quantity = 60, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/61FvzEAxEfL._AC_UF1000,1000_QL80_.jpg", "https://crdms.images.consumerreports.org/prod/products/cr/models/403495-full-size-desktops-acer-aspire-tc-390-ua91-10020209.png", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC7Gi2HZT6fKYd8_-2Ja6r4ra9CZxKhsER6lzMWBhF6WdwQRHF2AAKEmND_yifavnxzd4&usqp=CAU" } },
                new Product { Id = 16,CreatedAt = DateTime.UtcNow, Name = "MSI MPG Trident 3", Brand = "MSI", Price = 1199.99m, Category = "IT Equipment", SubCategory = "Desktop Computers", Quantity = 20, Warranty = 12, Images = new string[] { "https://asset.msi.com/resize/image/global/product/product_5_20200430090514_5eaa244a51b97.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png", "https://static.fnac-static.com/multimedia/Images/FR/MDM/b2/0f/ef/15667122/1520-2/tsp20240917000831/PC-Gaming-MSI-MPG-Trident-3-10SI-017EU-Intel-Core-i5-8-Go-RAM-512-Go-D-Noir.jpg", "https://asset.msi.com/resize/image/global/product/product_1616117954b90e22a7982983c1a3450e07f8b6fbb9.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png" } },
                new Product { Id = 17,CreatedAt = DateTime.UtcNow, Name = "CyberPowerPC Gamer Xtreme", Brand = "CyberPowerPC", Price = 1299.99m, Category = "IT Equipment", SubCategory = "Desktop Computers", Quantity = 15, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/71DvG2FjM+L.jpg" } },
                new Product { Id = 18,CreatedAt = DateTime.UtcNow, Name = "Alienware Aurora R13", Brand = "Dell", Price = 1999.99m, Category = "IT Equipment", SubCategory = "Desktop Computers", Quantity = 10, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/71eMGaxGv2L._UF894,1000_QL80_.jpg" } },

                
                new Product { Id = 19,CreatedAt = DateTime.UtcNow, Name = "Dell UltraSharp U2720Q", Brand = "Dell", Price = 549.99m, Category = "IT Equipment", SubCategory = "Monitors", Quantity = 40, Warranty = 36, Images = new string[] { "https://cdn.allmarket.ge/2405/34/20/33/9e0a1d3fd74e430fb486974666ca8615/49102-438979.jpg" } },
                new Product { Id = 20,CreatedAt = DateTime.UtcNow, Name = "LG UltraFine 4K 27UN850-W", Brand = "LG", Price = 499.99m, Category = "IT Equipment", SubCategory = "Monitors", Quantity = 35, Warranty = 24, Images = new string[] { "https://media.us.lg.com/transform/ecomm-PDPGallery-1100x730/ee581b8d-6d39-4746-b018-87a5416b8b9e/md07516743-zoom-01-v1-jpg?io=transform:fill,width:596" } },
                new Product { Id = 21,CreatedAt = DateTime.UtcNow, Name = "ASUS ProArt PA278QV", Brand = "ASUS", Price = 349.99m, Category = "IT Equipment", SubCategory = "Monitors", Quantity = 30, Warranty = 36, Images = new string[] { "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr0-DsIF-ouxJjhMJVeNGG5irTa9MMfBuq1A&s" } },
                new Product { Id = 22,CreatedAt = DateTime.UtcNow, Name = "Samsung Odyssey G7", Brand = "Samsung", Price = 699.99m, Category = "IT Equipment", SubCategory = "Monitors", Quantity = 25, Warranty = 24, Images = new string[] { "https://geekspot.ge/files/products/FIdjly4uT61KNsUsdkd2RsjSyiaUUP.png" } },
                new Product { Id = 23,CreatedAt = DateTime.UtcNow, Name = "Acer Predator XB273K", Brand = "Acer", Price = 799.99m, Category = "IT Equipment", SubCategory = "Monitors", Quantity = 20, Warranty = 24, Images = new string[] { "https://cdn.uc.assets.prezly.com/3477f3ff-2a8e-46a1-8f25-a1f0f4ff0629/-/preview/600x600/" } },
                new Product { Id = 24,CreatedAt = DateTime.UtcNow, Name = "BenQ PD3200U", Brand = "BenQ", Price = 749.99m, Category = "IT Equipment", SubCategory = "Monitors", Quantity = 15, Warranty = 36, Images = new string[] { "https://m.media-amazon.com/images/I/61Dg42qrTIL._UF1000,1000_QL80_.jpg" } },
                new Product { Id = 25,CreatedAt = DateTime.UtcNow, Name = "HP Z27k G3", Brand = "HP", Price = 399.99m, Category = "IT Equipment", SubCategory = "Monitors", Quantity = 30, Warranty = 36, Images = new string[] { "https://cdn11.bigcommerce.com/s-alitpcfiof/images/stencil/1280x1280/products/24183/25014/810030056287__78799.1697000947.png?c=1" } },
                new Product { Id = 26,CreatedAt = DateTime.UtcNow, Name = "ViewSonic VP2768-4K", Brand = "ViewSonic", Price = 449.99m, Category = "IT Equipment", SubCategory = "Monitors", Quantity = 25, Warranty = 36, Images = new string[] { "https://m.media-amazon.com/images/I/71iLyXnxOwL._UF894,1000_QL80_.jpg" } },
                new Product { Id = 27,CreatedAt = DateTime.UtcNow, Name = "MSI Optix MAG274QRF-QD", Brand = "MSI", Price = 529.99m, Category = "IT Equipment", SubCategory = "Monitors", Quantity = 20, Warranty = 24, Images = new string[] { "https://m.media-amazon.com/images/I/61F0asVBnqL.jpg" } },

             
                new Product { Id = 28,CreatedAt = DateTime.UtcNow, Name = "Intel Core i9-12900K", Brand = "Intel", Price = 599.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 30, Warranty = 36, Images = new string[] { "https://m.media-amazon.com/images/I/51x19d4dPuL._UF894,1000_QL80_.jpg" } },
                new Product { Id = 29,CreatedAt = DateTime.UtcNow, Name = "AMD Ryzen 9 5950X", Brand = "AMD", Price = 549.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 35, Warranty = 36, Images = new string[] { "https://www.amd.com/content/dam/amd/en/images/products/processors/ryzen/2505503-ryzen-9-5900x.jpg" } },
                new Product { Id = 30, CreatedAt = DateTime.UtcNow, Name = "Intel Core i7-12700K", Brand = "Intel", Price = 419.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 40, Warranty = 36, Images = new string[] { "https://www.bhphotovideo.com/images/fb/intel_bx8071512700k_core_i7_12700k_8_core_lga_1663646.jpg" } },
                new Product { Id = 31, CreatedAt = DateTime.UtcNow, Name = "AMD Ryzen 7 5800X", Brand = "AMD", Price = 349.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 45, Warranty = 36, Images = new string[] { "https://www.amd.com/content/dam/amd/en/images/products/processors/ryzen/2505503-ryzen-7-5800x.jpg" } },
                new Product { Id = 32,CreatedAt = DateTime.UtcNow, Name = "Intel Core i5-12600K", Brand = "Intel", Price = 289.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 50, Warranty = 36, Images = new string[] { "https://ww.ge/image/cache/catalog/produqcia/287/intel-core-i5-12600k-4-9-ghz_1-515x515.jpg" } },
                new Product { Id = 33, CreatedAt = DateTime.UtcNow, Name = "AMD Ryzen 5 5600X", Brand = "AMD", Price = 199.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 60, Warranty = 36, Images = new string[] { "https://www.amd.com/content/dam/amd/en/images/products/processors/ryzen/2505503-ryzen-5-5600x.jpg" } },
                new Product { Id = 34,  CreatedAt = DateTime.UtcNow, Name = "Intel Core i9-11900K", Brand = "Intel", Price = 399.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 25, Warranty = 36, Images = new string[] { "https://i5.walmartimages.com/seo/Intel-Core-i9-11900K-Desktop-Processor-8-Cores-up-to-5-3-GHz-Unlocked-LGA1200-Intel-500-Series-chipset-125W_7016f9ad-229f-456e-b8ca-49b44aaef7c9.52a30840572b937718e286362a2f96f2.jpeg" } },
                new Product { Id = 35,CreatedAt = DateTime.UtcNow, Name = "AMD Ryzen 9 5900X", Brand = "AMD", Price = 449.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 30, Warranty = 36, Images = new string[] { "https://www.amd.com/content/dam/amd/en/images/products/processors/ryzen/2505503-ryzen-9-5900x.jpg" } },
                new Product { Id = 36,CreatedAt = DateTime.UtcNow, Name = "Intel Core i3-12100", Brand = "Intel", Price = 129.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 70, Warranty = 36, Images = new string[] { "https://pczone.ge/wp-content/uploads/2023/10/1694702873_Intel-Core-i3-12.jpg" } },

                new Product { Id = 37,CreatedAt = DateTime.UtcNow, Name = "NVIDIA GeForce RTX 3090", Brand = "NVIDIA", Price = 1499.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 10, Warranty = 36, Images = new string[] { "https://m.media-amazon.com/images/I/51K36OrmxLL._AC_SL1500_.jpg" } },
                new Product { Id = 38,CreatedAt = DateTime.UtcNow, Name = "AMD Radeon RX 6900 XT", Brand = "AMD", Price = 999.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 15, Warranty = 36, Images = new string[] { "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQygnZulSmOlSoCNVVKVfsGwTGM3CNhhTrNtw&s" } },
                new Product { Id = 39,CreatedAt = DateTime.UtcNow, Name = "NVIDIA GeForce RTX 3080", Brand = "NVIDIA", Price = 799.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 20, Warranty = 36, Images = new string[] { "https://m.media-amazon.com/images/I/71ZmRXZcnXS._AC_SL1500_.jpg" } },
                new Product { Id = 40,CreatedAt = DateTime.UtcNow, Name = "AMD Radeon RX 6800 XT", Brand = "AMD", Price = 649.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 25, Warranty = 36, Images = new string[] { "https://m.media-amazon.com/images/I/71doJrnea0L.jpg" } },
                new Product { Id = 41,CreatedAt = DateTime.UtcNow, Name = "NVIDIA GeForce RTX 3070", Brand = "NVIDIA", Price = 499.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 30, Warranty = 36, Images = new string[] { "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs9awI7Nz3WHAafgAxNp283o9lbjzhX-rNxQ&s" } },
                new Product { Id = 42,CreatedAt = DateTime.UtcNow, Name = "AMD Radeon RX 6700 XT", Brand = "AMD", Price = 479.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 35, Warranty = 36, Images = new string[] { "https://static.my.ge/mymarket/photos/large/0507/25003323_2.jpg?v=22" } },
                new Product { Id = 43,CreatedAt = DateTime.UtcNow, Name = "NVIDIA GeForce RTX 3060 Ti", Brand = "NVIDIA", Price = 399.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 40, Warranty = 36, Images = new string[] { "https://m.media-amazon.com/images/I/818JWCrFAKL.jpg" } },
                new Product { Id = 44,CreatedAt = DateTime.UtcNow, Name = "AMD Radeon RX 6600 XT", Brand = "AMD", Price = 379.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 45, Warranty = 36, Images = new string[] { "https://asset.msi.com/resize/image/global/product/product_162761041853b534486be297dc55c4bc40ffe92b45.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png" } },
                new Product { Id = 45, CreatedAt = DateTime.UtcNow, Name = "NVIDIA GeForce RTX 3050", Brand = "NVIDIA", Price = 249.99m, Category = "IT Equipment", SubCategory = "PC Components", Quantity = 50, Warranty = 36, Images = new string[] { "https://asset.msi.com/resize/image/global/product/product_1641350745e8eaaffc8f84377957eb93490d5a3f6e.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png" } },

               
                new Product { Id = 46,  CreatedAt = DateTime.UtcNow, Name = "HP LaserJet Pro MFP M428fdw", Brand = "HP", Price = 499.99m, Category = "IT Equipment", SubCategory = "Printers", Quantity = 25, Warranty = 12, Images = new string[] { "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrUxg-4QrV2saojfUvyTIRO2p-vf9Wolll0Q&s" } },
                new Product { Id = 47,CreatedAt = DateTime.UtcNow, Name = "Epson WorkForce Pro WF-4740", Brand = "Epson", Price = 299.99m, Category = "IT Equipment", SubCategory = "Printers", Quantity = 30, Warranty = 12, Images = new string[] { "https://images-na.ssl-images-amazon.com/images/I/61oBWaIvW4L._AC_UL495_SR435,495_.jpg" } },
                new Product { Id = 48,CreatedAt = DateTime.UtcNow, Name = "Brother HL-L8360CDW", Brand = "Brother", Price = 399.99m, Category = "IT Equipment", SubCategory = "Printers", Quantity = 20, Warranty = 12, Images = new string[] { "https://www.brother-usa.com/-/media/brother/product-catalog-media/images/2022/07/18/08/25/hll8360cdw_left.png" } },
                new Product { Id = 49,CreatedAt = DateTime.UtcNow, Name = "Canon imageCLASS MF644Cdw", Brand = "Canon", Price = 349.99m, Category = "IT Equipment", SubCategory = "Printers", Quantity = 25, Warranty = 12, Images = new string[] { "https://m.media-amazon.com/images/I/61KVkrwLikL.jpg" } },
                new Product { Id = 50,CreatedAt = DateTime.UtcNow, Name = "Xerox VersaLink C405", Brand = "Xerox", Price = 599.99m, Category = "IT Equipment", SubCategory = "Printers", Quantity = 15, Warranty = 12, Images = new string[] { "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-cFj1-Ji358onjPFvR1Es6NoUT4kcO2S33A&s" } },
                new Product { Id = 51,CreatedAt = DateTime.UtcNow, Name = "HP OfficeJet Pro 9025e", Brand = "HP", Price = 329.99m, Category = "IT Equipment", SubCategory = "Printers", Quantity = 35, Warranty = 12, Images = new string[] { "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-lFcPyHGzWbvrgZcbvSR1aAriFqvT1_NJ5g&s" } },
                new Product { Id = 52,CreatedAt = DateTime.UtcNow, Name = "Epson EcoTank ET-4760", Brand = "Epson", Price = 399.99m, Category = "IT Equipment", SubCategory = "Printers", Quantity = 20, Warranty = 12, Images = new string[] { "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgaRjFDShIZPqogNFFDb3Onr-gggHVigj3xg&s" } },
                new Product { Id = 53,CreatedAt = DateTime.UtcNow, Name = "Brother MFC-J995DW", Brand = "Brother", Price = 249.99m, Category = "IT Equipment", SubCategory = "Printers", Quantity = 30, Warranty = 12, Images = new string[] { "https://i.pcmag.com/imagery/reviews/01TvutTihGwb7hAlCYZWZqb-2..v1569469972.jpg" } },
                new Product { Id = 54,CreatedAt = DateTime.UtcNow, Name = "Lexmark MC3224dwe", Brand = "Lexmark", Price = 199.99m, Category = "IT Equipment", SubCategory = "Printers", Quantity = 25, Warranty = 12, Images = new string[] { "https://cdn.mos.cms.futurecdn.net/UQfDcqTiVKw5kUUDGLZWmY.jpg" } },

                new Product { Id = 55,CreatedAt = DateTime.UtcNow, Name = "Logitech MX Keys", Brand = "Logitech", Price = 99.99m, Category = "IT Equipment", SubCategory = "Keyboards", Quantity = 50, Warranty = 24, Images = new string[] { "https://resource.logitech.com/w_800,c_lpad,ar_16:9,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/logitech/en/products/keyboards/mx-keys-s/migration-assets-for-delorean-2025/gallery/mx-keys-s-top-view-black-us.png?v=1" } },
                new Product { Id = 56,CreatedAt = DateTime.UtcNow, Name = "Corsair K100 RGB", Brand = "Corsair", Price = 199.99m, Category = "IT Equipment", SubCategory = "Keyboards", Quantity = 30, Warranty = 24, Images = new string[] { "https://m.media-amazon.com/images/I/617biaJfmOS._AC_SL1200_.jpg" } },
                new Product { Id = 57,CreatedAt = DateTime.UtcNow, Name = "Razer BlackWidow V3", Brand = "Razer", Price = 139.99m, Category = "IT Equipment", SubCategory = "Keyboards", Quantity = 40, Warranty = 24, Images = new string[] { "https://gamezone.ge/images/detailed/21/Untitled-1_9bzw-zk.jpg" } },
                new Product { Id = 58,CreatedAt = DateTime.UtcNow, Name = "SteelSeries Apex Pro", Brand = "SteelSeries", Price = 179.99m, Category = "IT Equipment", SubCategory = "Keyboards", Quantity = 25, Warranty = 24, Images = new string[] { "https://i5.walmartimages.com/seo/SteelSeries-Apex-Pro-Mechanical-Gaming-Keyboard-Adjustable-Actuation-Switches-OLED-Smart-Display-RGB-Backlit-With-Rapid-Tap_3f00a880-ef9e-4309-99b6-22207ed4dad9.e2ba5c738d304403b24c7b95515f86d1.jpeg" } },
                new Product { Id = 59,CreatedAt = DateTime.UtcNow, Name = "Keychron K8", Brand = "Keychron", Price = 89.99m, Category = "IT Equipment", SubCategory = "Keyboards", Quantity = 45, Warranty = 12, Images = new string[] { "https://i.rtings.com/assets/products/XSuXWhSC/keychron-k8-pro-k2-pro-k3-pro-k4-pro-etc/design-medium.jpg?format=auto" } },
                new Product { Id = 60,CreatedAt = DateTime.UtcNow, Name = "HyperX Alloy Origins Core", Brand = "HyperX", Price = 79.99m, Category = "IT Equipment", SubCategory = "Keyboards", Quantity = 35, Warranty = 24, Images = new string[] { "https://row.hyperx.com/cdn/shop/products/hyperx_alloy_origins_core_no_3_angled_right.jpg?v=1663701487" } },
                new Product { Id = 61,CreatedAt = DateTime.UtcNow, Name = "Dell KB522", Brand = "Dell", Price = 49.99m, Category = "IT Equipment", SubCategory = "Keyboards", Quantity = 60, Warranty = 12, Images = new string[] { "https://www.dateks.lv/images/pic/2400/2400/740/690.jpg" } },
                new Product { Id = 62,CreatedAt = DateTime.UtcNow, Name = "Apple Magic Keyboard", Brand = "Apple", Price = 99.00m, Category = "IT Equipment", SubCategory = "Keyboards", Quantity = 40, Warranty = 12, Images = new string[] { "https://cache.willhaben.at/mmo/1/158/185/2341_-1413090385.jpg" } },
                new Product { Id = 63,CreatedAt = DateTime.UtcNow, Name = "ASUS ROG Strix Scope RX", Brand = "ASUS", Price = 159.99m, Category = "IT Equipment", SubCategory = "Keyboards", Quantity = 20, Warranty = 24, Images = new string[] { "https://m.media-amazon.com/images/I/71zoNxE+LiL._AC_SL1500_.jpg" } },

               
                new Product { Id = 64,CreatedAt = DateTime.UtcNow, Name = "Logitech MX Master 3", Brand = "Logitech", Price = 99.99m, Category = "IT Equipment", SubCategory = "Mice", Quantity = 60, Warranty = 24, Images = new string[] { "https://i.rtings.com/assets/products/UPOdtAiR/logitech-mx-master-3/design-large.jpg?format=auto" } },
                new Product { Id = 65,CreatedAt = DateTime.UtcNow, Name = "Razer DeathAdder V2", Brand = "Razer", Price = 69.99m, Category = "IT Equipment", SubCategory = "Mice", Quantity = 50, Warranty = 24, Images = new string[] { "https://www.boostboxx.com/en/media/catalog/product/cache/9/image/9df78eab33525d08d6e5fb8d27136e95/r/a/razer_deathadder_v2_usb_maus-83519_01_3000px.png" } },
                new Product { Id = 66,CreatedAt = DateTime.UtcNow, Name = "SteelSeries Rival 600", Brand = "SteelSeries", Price = 79.99m, Category = "IT Equipment", SubCategory = "Mice", Quantity = 40, Warranty = 24, Images = new string[] { "https://m.media-amazon.com/images/I/51UnFzpQ-RL.jpg" } },
                new Product { Id = 67,CreatedAt = DateTime.UtcNow, Name = "Corsair Dark Core RGB Pro", Brand = "Corsair", Price = 79.99m, Category = "IT Equipment", SubCategory = "Mice", Quantity = 35, Warranty = 24, Images = new string[] { "https://assets.corsair.com/image/upload/f_auto,q_auto/v1/akamai/pdp/darkcore-rgb-pro/images/dark_core_pro_wired.png" } },
                new Product { Id = 68,CreatedAt = DateTime.UtcNow, Name = "Microsoft Surface Mouse", Brand = "Microsoft", Price = 59.99m, Category = "IT Equipment", SubCategory = "Mice", Quantity = 45, Warranty = 12, Images = new string[] { "https://cdn-dynmedia-1.microsoft.com/is/image/microsoftcorp/gldn-WS300001-SurfA-Bendis-b00-1?qlt=90&wid=1253&hei=705&extendN=0.12,0.12,0.12,0.12&bgc=FFFFFFFF&fmt=jpg" } },
                new Product { Id = 69,CreatedAt = DateTime.UtcNow, Name = "HP Z3700", Brand = "HP", Price = 24.99m, Category = "IT Equipment", SubCategory = "Mice", Quantity = 70, Warranty = 12, Images = new string[] { "https://assets.ee.ge/elit-product-mobile-images/IMG-000061990_47-1.jpg" } },
                new Product { Id = 70,CreatedAt = DateTime.UtcNow, Name = "ASUS ROG Gladius II", Brand = "ASUS", Price = 89.99m, Category = "IT Equipment", SubCategory = "Mice", Quantity = 30, Warranty = 24, Images = new string[] { "https://www.geekspot.ge/files/products/1uCqRF09UdGIfQF7v63eDyvd4Iw6FZ.png" } },
                new Product { Id = 71,CreatedAt = DateTime.UtcNow, Name = "Apple Magic Mouse 2", Brand = "Apple", Price = 79.00m, Category = "IT Equipment", SubCategory = "Mice", Quantity = 40, Warranty = 12, Images = new string[] { "https://i.rtings.com/assets/products/B573oCMs/apple-magic-mouse-2/design-large.jpg?format=auto" } },
                new Product { Id = 72,CreatedAt = DateTime.UtcNow, Name = "HyperX Pulsefire Haste", Brand = "HyperX", Price = 49.99m, Category = "IT Equipment", SubCategory = "Mice", Quantity = 50, Warranty = 24, Images = new string[] { "https://www.hp.com/es-es/shop/Html/Merch/Images/c07721065_500x367.jpg" } },

               
                new Product { Id = 73,CreatedAt = DateTime.UtcNow, Name = "Dell PowerEdge R750", Brand = "Dell", Price = 3499.99m, Category = "IT Equipment", SubCategory = "Servers", Quantity = 5, Warranty = 36, Images = new string[] { "https://servermall.com/upload/iblock/6a2/o0vdc30wz5tzrwpdp764g29lrkn0xsir/Dell_EMC_PowerEdge_R750_Front_Bezel-_1_.jpeg" } },
                new Product { Id = 74,CreatedAt = DateTime.UtcNow, Name = "HPE ProLiant DL380 Gen10", Brand = "HPE", Price = 2999.99m, Category = "IT Equipment", SubCategory = "Servers", Quantity = 5, Warranty = 36, Images = new string[] { "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUX4iAKsGRUiSRMqLeTXG8MV4h1Dql5R5_lg&s" } },
                new Product { Id = 75,CreatedAt = DateTime.UtcNow, Name = "Lenovo ThinkSystem SR650", Brand = "Lenovo", Price = 2799.99m, Category = "IT Equipment", SubCategory = "Servers", Quantity = 5, Warranty = 36, Images = new string[] { "https://www.i-tech.com.au/media/catalog/product/cache/d90074b510a9e8618355b82ff6546f51/s/v/svl-7x06a0ezau.jpg" } },
                new Product { Id = 76,CreatedAt = DateTime.UtcNow, Name = "Cisco UCS C240 M6", Brand = "Cisco", Price = 3999.99m, Category = "IT Equipment", SubCategory = "Servers", Quantity = 3, Warranty = 36, Images = new string[] { "https://cdn.cs.1worldsync.com/e8/a3/e8a3943e-c05a-4f80-aada-0739dc1f4a2f.jpg" } },
                new Product { Id = 77,CreatedAt = DateTime.UtcNow, Name = "Supermicro SYS-2029U-TN24R4T", Brand = "Supermicro", Price = 2499.99m, Category = "IT Equipment", SubCategory = "Servers", Quantity = 4, Warranty = 36, Images = new string[] { "https://www.broadberry.co.uk/system_files/images/system_images/cut/2029U-E1CRTPmainimg.jpg" } },
                new Product { Id = 78,CreatedAt = DateTime.UtcNow, Name = "Fujitsu PRIMERGY RX2540 M5", Brand = "Fujitsu", Price = 3199.99m, Category = "IT Equipment", SubCategory = "Servers", Quantity = 3, Warranty = 36, Images = new string[] { "https://www.fujitsu.com/kr/imagesgig5/img01_tcm119-5327407_tcm119-5309118-32.jpg" } },
                new Product { Id = 79,CreatedAt = DateTime.UtcNow, Name = "IBM Power System S914", Brand = "IBM", Price = 4999.99m, Category = "IT Equipment", SubCategory = "Servers", Quantity = 2, Warranty = 36, Images = new string[] { "https://cdn11.bigcommerce.com/s-sughhmv/images/stencil/1280x1280/products/875/1412/9009-rack__04774.1747772269.jpg?c=2" } },
                new Product { Id = 80,CreatedAt = DateTime.UtcNow, Name = "Oracle Server X8-2", Brand = "Oracle", Price = 4499.99m, Category = "IT Equipment", SubCategory = "Servers", Quantity = 2, Warranty = 36, Images = new string[] { "https://docs.oracle.com/cd/E93361_01/graphics/X7-2L-beauty.png" } },
                new Product { Id = 81,CreatedAt = DateTime.UtcNow, Name = "ASUS RS520-E10-RS12U", Brand = "ASUS", Price = 2299.99m, Category = "IT Equipment", SubCategory = "Servers", Quantity = 4, Warranty = 36, Images = new string[] { "https://dlcdnwebimgs.asus.com/gain/4033c83d-1006-480a-a888-b5dfacf97d12/w600" } },

               
                new Product { Id = 82,CreatedAt = DateTime.UtcNow, Name = "Cisco Catalyst 2960-X", Brand = "Cisco", Price = 899.99m, Category = "IT Equipment", SubCategory = "Network Switches", Quantity = 15, Warranty = 36, Images = new string[] { "https://www.cisco.com/c/dam/assets/support/product-images/series/series-switches-catalyst-2960-x-series-switches-alternate3.jpg" } },
                new Product { Id = 83,CreatedAt = DateTime.UtcNow, Name = "NETGEAR ProSAFE GS724T", Brand = "NETGEAR", Price = 249.99m, Category = "IT Equipment", SubCategory = "Network Switches", Quantity = 20, Warranty = 24, Images = new string[] { "https://www.itechstorm.com/wp-content/uploads/2012/02/Netgear_GS748T-1.jpg" } },
                new Product { Id = 84,CreatedAt = DateTime.UtcNow, Name = "TP-Link TL-SG2428P", Brand = "TP-Link", Price = 299.99m, Category = "IT Equipment", SubCategory = "Network Switches", Quantity = 25, Warranty = 24, Images = new string[] { "https://www.dipolnet.com/dimages/pl/pict/n29969+++.jpg" } },
                new Product { Id = 85,CreatedAt = DateTime.UtcNow, Name = "Ubiquiti UniFi USW-24-PoE", Brand = "Ubiquiti", Price = 399.99m, Category = "IT Equipment", SubCategory = "Network Switches", Quantity = 15, Warranty = 24, Images = new string[] { "https://m.media-amazon.com/images/I/41bpyyvrrcL.jpg" } },
                new Product { Id = 86, CreatedAt = DateTime.UtcNow,Name = "HPE Aruba 2530-24G", Brand = "HPE", Price = 499.99m, Category = "IT Equipment", SubCategory = "Network Switches", Quantity = 10, Warranty = 36, Images = new string[] { "https://ictdevices.com/img/upload/J9776A.jpg" } },
                new Product { Id = 87,CreatedAt = DateTime.UtcNow, Name = "Dell PowerSwitch N2048P", Brand = "Dell", Price = 599.99m, Category = "IT Equipment", SubCategory = "Network Switches", Quantity = 12, Warranty = 36, Images = new string[] { "https://res.cloudinary.com/dmwxtja1g/image/upload/c_lpad,dpr_1.0,f_auto,q_80/v1/media/catalog/product/n/2/n2048p_back_zoom.jpg?_i=AB" } },
                new Product { Id = 88,CreatedAt = DateTime.UtcNow, Name = "Juniper EX2300-24P", Brand = "Juniper", Price = 1299.99m, Category = "IT Equipment", SubCategory = "Network Switches", Quantity = 8, Warranty = 36, Images = new string[] { "https://media.router-switch.com/media/mf_webp/jpg/media/catalog/product/cache/b90fceee6a5fa7acd36a04c7b968181c/j/u/juniper-ex2300-24p.webp" } },
                new Product { Id = 89,CreatedAt = DateTime.UtcNow, Name = "FortiSwitch 124E", Brand = "Fortinet", Price = 799.99m, Category = "IT Equipment", SubCategory = "Network Switches", Quantity = 10, Warranty = 36, Images = new string[] { "https://www.corporatearmor.com/wp-content/uploads/2020/11/FS124E_blog_graphic.png" } },
                new Product { Id = 90,CreatedAt = DateTime.UtcNow, Name = "ZyXEL GS1920-24", Brand = "ZyXEL", Price = 199.99m, Category = "IT Equipment", SubCategory = "Network Switches", Quantity = 30, Warranty = 24, Images = new string[] { "https://www.zyxelguard.com/images/switches/1920-Series/GS1920-24HP.jpg" } }
            };
        }
    }
}
